(feat) engine.create creates an EC2 instance
drone-runners/drone-runner-aws pull request #1
Opened 2021-04-22 14:45 UTC by tphoney

2021-05-05 19:08 UTC, bradrydzewski requested changes

2021-05-12 12:47 UTC, tphoney commented on engine/spec.go
> +		KeyPair       string  `json:"key_pair,omitempty"`
i added this in because it made debug easier if you wanted access. otherwise there is no way to get into the new system

2021-05-12 12:47 UTC, tphoney commented on .vscode/launch.json
> +{
agreed, this was my helper

2021-05-12 12:48 UTC, tphoney commented on internal/userdata/userdata.go
> +- name: drone
i changed when i had issues with the cloud init template, but we can flip back to root

2021-05-12 12:48 UTC, tphoney commented on internal/platform/util_test.go
> +	"github.com/stretchr/testify/assert"
we should talk about this

2021-05-18 09:51 UTC, tphoney commented on README.md
> +
👍

2021-05-18 09:51 UTC, tphoney commented on internal/userdata/userdata.go
> +- name: drone
fixed

2021-05-18 09:51 UTC, tphoney commented on internal/platform/util_test.go
> +	"github.com/stretchr/testify/assert"
fixed

2021-05-18 09:52 UTC, tphoney commented on .vscode/launch.json
> +{
fixed

2021-05-18 09:52 UTC, tphoney commented on engine/engine.go
> +	var userDataWithSSH string
fixed

2021-05-18 09:52 UTC, tphoney commented on engine/engine.go
> +	publickey, privatekey, err := sshkey.GeneratePair()
fixed

2021-05-27 22:46 UTC, bradrydzewski approved these changes

2021-05-28 08:20 UTC, merged