changes in clound init script for installling tmate
drone-runners/drone-runner-aws pull request #189
Opened 2022-10-30 20:12 UTC by HenAmar

# Commit Checklist

Thank you for creating a pull request! To help us review / merge this can you make sure that your PR adheres as much as possible to the following.

## The Basics

If you are adding new functionality, please provide evidence of the new functionality.

2022-12-19 11:37 UTC, shubham149 commented on internal/cloudinit/cloudinit.go
> +- 'mkdir /addon'
Addon volume is not used in vms. It is used specifically in k8 only.

2022-12-19 12:51 UTC, shubham149 commented on internal/cloudinit/cloudinit.go
> +- 'mkdir /addon'
Also, this needs to work for both linux amd64 and linux arm64

2022-12-19 12:51 UTC, shubham149 commented on internal/cloudinit/cloudinit.go
> +- 'wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz -O /addon/tmate.xz'
This needs to work for both linux amd64 and linux arm64

2022-12-23 07:23 UTC, tphoney requested changes
There are a couple of things: 

1. you have not implemented this for the amazon linux build.
2. most importantly there is no way to disable this functionality. This installation block should be wrapped in a conditional. Ideally we should be able to disable/enable this with an environment variable. 
3. If we are enabling this via cloud init, as seen. Then we should remove the alternate way of installing it for drone. 
4. Are there binaries for mac ?

2022-12-27 18:38 UTC, HenAmar commented
Hey @tphoney :

> 1. you have not implemented this for the amazon linux build. 
Added

> 2. most importantly there is no way to disable this functionality. This installation block should be wrapped in a conditional. Ideally we should be able to disable/enable this with an environment variable.
I took advantage of the existing "DRONE_TMATE_ENABLED" var and populate it all the way to use it. 

> 3. If we are enabling this via cloud init, as seen. Then we should remove the alternate way of installing it for drone.
I put the foundation for it and it should be easy to do it now, but I would like it to be done in a different scope and not part of this PR

> 4. Are there binaries for mac ?
No.

2023-01-03 11:36 UTC, tphoney approved these changes

2023-01-03 13:09 UTC, eoinmcafee00 approved these changes

2023-01-03 16:31 UTC, merged