(feat) - osx support with vmware fusion
drone-runners/drone-runner-aws pull request #92
Opened 2022-04-13 12:12 UTC by eoinmcafee00

2022-04-13 14:43 UTC, tphoney reviewed
you will need to rebase, and squash your commits

2022-04-13 15:01 UTC, eoinmcafee00 commented
@tphoney done

2022-04-13 15:20 UTC, tphoney requested changes

2022-04-14 08:42 UTC, eoinmcafee00 commented on command/config/config.go
> +		Version string `json:"version,omitempty"`
Version is new, it's required for vmx config - it tell the VM which version of ISO is being used. I.e. darwin20 for bigSur

2022-04-14 08:42 UTC, eoinmcafee00 commented on command/config/config.go
> +		Memory        int64  `json:"memory,omitempty" yaml:"memory"`
It does.

2022-04-14 08:42 UTC, eoinmcafee00 commented on internal/drivers/vmfusion/pool.go
> +	return nil
Good point, i had actually mean't to do that but missed it.

2022-04-14 09:18 UTC, eoinmcafee00 commented on internal/drivers/vmfusion/pool.go
> +	return nil
I just checked, you don't need it to be running. "vmrun" works regardless

2022-04-14 15:13 UTC, merged